version: "3"
services:

  frontend:
    build:
      dockerfile: Dockerfile
      context: ./daily-vocab-fe
    ports:
      - 3000:80 
    depends_on: 
      - backend

  backend:
    build:
      dockerfile: Dockerfile
      context: ./daily-vocab-be

    ports:
      - 8080:8080
    depends_on: 
      - some-postgres

  some-postgres:
    image: postgres
    volumes:
      - ./database:/var/lib/postgresql/data
    ports: 
      - 5000:5432
    environment: 
      POSTGRES_PASSWORD: mysecretpassword